/**
 * The layout and the routing table.
 *
 * A route maps a URL to a component. That mapping is what makes the back
 * button, a bookmark and a shared link work in an application that never
 * reloads the page — the URL stays the source of truth for what is on
 * screen, instead of a variable in memory that only this tab knows about.
 */
import { Link, Route, Routes } from 'react-router-dom';

import { CAPTURED_AT, IS_DEMO } from './demo/demo';
import { PatientDetail } from './pages/PatientDetail';
import { WardBoard } from './pages/WardBoard';
import { WardList } from './pages/WardList';

const CAPTURED_ON = new Date(CAPTURED_AT).toLocaleDateString('en-GB', {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
  timeZone: 'UTC',
});

/**
 * What this page is, said once, at the top, before anybody reads a number
 * off it. A demonstration that does not admit to being one is a lie with a
 * chart on it.
 */
function DemoNotice() {
  return (
    <p className="demo-notice">
      <strong>Demo.</strong> Synthetic patients, generated by the simulator in this repository — no
      real clinical data has ever been in this project. The screens are the real dashboard, reading
      responses recorded from the real API on {CAPTURED_ON} instead of a live one; timestamps are
      moved forward so the intervals still read correctly. The handover notes were written by a
      language model and each one passed the verifier that rejects any figure absent from the
      record.
    </p>
  );
}

export function App() {
  return (
    <div className="layout">
      <header className="masthead">
        <h1>
          <Link to="/" style={{ textDecoration: 'none' }}>
            VitaLink
          </Link>
        </h1>
        <p>Ward board — synthetic data</p>
      </header>

      {IS_DEMO && <DemoNotice />}

      <Routes>
        <Route path="/" element={<WardList />} />
        <Route path="/wards/:ward" element={<WardBoard />} />
        <Route path="/admissions/:admissionId" element={<PatientDetail />} />
        <Route path="*" element={<p className="state">No such page.</p>} />
      </Routes>
    </div>
  );
}
